apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-microservice
  labels:
    app: config-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-microservice
  template:
    metadata:
      labels:
        app: config-microservice
    spec:
      containers:
      - name: config
        image: eu.gcr.io/PROJECT_NAME/config-microservice:latest
        ports:
        - name: http-server
          containerPort: 8088
        imagePullPolicy: Always
